CREATE TABLE [dbo].[VGTable]
(
	[UPC] INT NOT NULL PRIMARY KEY, 
    [TITLE] TEXT NULL, 
    [DESCRIPTION] TEXT NULL, 
    [RELEASEDATE] DATE NULL, 
    [PLATFORM] TEXT NULL, 
    [PURCHASEDATE] DATE NULL, 
    [PURCHASEAMT] MONEY NULL, 
    [PURCHASELOCATION] TEXT NULL, 
    [RETAILAMT] MONEY NULL, 
    [DISCOUNT] FLOAT NULL, 
    [DATEADDED] DATE NULL, 
    [ADDEDBY] TEXT NULL
)
