CREATE TABLE [dbo].[VGTable]
(
	[ID] INT IDENTITY (1,1) NOT NULL,
	[UPC] TEXT NULL , 
    [TITLE] TEXT NULL, 
    [DESCRIPTION] TEXT NULL, 
    [RELEASEDATE] DATE NULL, 
    [PLATFORM] TEXT NULL, 
    [PURCHASEDATE] DATE NULL, 
    [PURCHASEAMT] TEXT NULL, 
    [PURCHASELOCATION] TEXT NULL, 
    [RETAILAMT] TEXT NULL, 
    [DISCOUNT] TEXT NULL, 
    [DATEADDED] DATE NULL, 
    [ADDEDBY] TEXT NULL, 
	[RATING] TEXT NULL,
	[DIGITAL] TEXT NULL,
    CONSTRAINT [PK_VGTable] PRIMARY KEY CLUSTERED ([ID] ASC)
)
